///////////////////////////////////////////////////////////
//  TStateStop.cs
//  Implementation of the Class TStateStop
//  Generated by Enterprise Architect
//  Created on:      29-¤»¤ë-2016 ¤U¤È 11:22:45
//  Original author: gihomn
///////////////////////////////////////////////////////////


using System.ComponentModel;
using System.Drawing;

namespace TStateMachineLibrary
{
    /// <summary>
    /// TStateStop
    /// </summary>
    [ToolboxItem(true)]
    public class TStateStop : TStateControl
    {

        //public TStateStop(Component AOwner) : base(AOwner)
        //{
        //}

        public TStateStop()
        {
        }

        ~TStateStop()
        {

        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="Element"></param>
        /// <param name="Canvas"></param>
        protected void PrepareCanvas(TVisualElement Element)
        {
            base.PrepareCanvas(Element);
            switch (Element)
            {
                case TVisualElement.Text:
                    Canvas.FontStyle = FontStyle.Bold;
                    break;
                case TVisualElement.Frame:
                    Canvas.MyPen.Color = Color.Red;
                    break;
            }
        }

    }//end TStateStop
}